In [1]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([0, 1])
print(np.shape(a))
print(np.shape(y))

(2, 3)
(2,)


In [2]:
m = np.mean(a, axis=0)
s = np.std(a, axis=0)
print(np.mean(a, axis=0))
print(np.std(a, axis=0))
a = (a - m)/s
print(a)

[ 2.5  3.5  4.5]
[ 1.5  1.5  1.5]
[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [3]:
ps = [0.23, 0.48, 0.64, 0.98]
np.sum([np.random.binomial(1,p=ps) for i in range(100000)], axis=0)

array([22890, 47979, 64111, 98004])

In [4]:
dropout = np.random.binomial(1, 0.1, size=100)
print(dropout)

[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]


In [5]:
mask = np.array([0, 1, 0])
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(x*mask.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 0]
 [0 5 0]
 [0 8 0]]


In [25]:
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
b = [[1, 2], [3, 4]]
a = np.lib.pad(a, ((0, 0), (1, 1), (1, 1)), 'constant')
print(a)
print(np.shape(a))
b = a[:, 2, 2][:, None, None]
print(b)
print(a * b)

[[[0 0 0 0]
  [0 1 2 0]
  [0 3 4 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 5 6 0]
  [0 7 8 0]
  [0 0 0 0]]]
(2, 4, 4)
[[[4]]

 [[8]]]
[[[ 0  0  0  0]
  [ 0  4  8  0]
  [ 0 12 16  0]
  [ 0  0  0  0]]

 [[ 0  0  0  0]
  [ 0 40 48  0]
  [ 0 56 64  0]
  [ 0  0  0  0]]]


In [10]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0:2, 0:3])

[[1 2 3]
 [4 5 6]]


In [44]:
a = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
b = np.argmax(a, axis=1)
print(b)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
