In [1]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([0, 1])
print(np.shape(a))
print(np.shape(y))

(2, 3)
(2,)


In [2]:
m = np.mean(a, axis=0)
s = np.std(a, axis=0)
print(np.mean(a, axis=0))
print(np.std(a, axis=0))
a = (a - m)/s
print(a)

[ 2.5  3.5  4.5]
[ 1.5  1.5  1.5]
[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [3]:
ps = [0.23, 0.48, 0.64, 0.98]
np.sum([np.random.binomial(1,p=ps) for i in range(100000)], axis=0)

array([23115, 47945, 64076, 97982])

In [7]:
dropout = np.random.binomial(1, 0.1, size=100)
print(dropout)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]


In [11]:
mask = np.array([0, 1, 0])
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(x*mask.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 0]
 [0 5 0]
 [0 8 0]]


In [37]:
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
b = [[1, 2], [3, 4]]
print(np.shape(a))
a = np.lib.pad(a, ((0, 0), (1, 1), (1, 1)), 'constant')
print(np.shape(a))
print(a[1,1,1]*a[0, 1, 2])

(2, 2, 2)
(2, 4, 4)
10
