In [1]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([0, 1])
print(np.shape(a))
print(np.shape(y))

(2, 3)
(2,)


In [5]:
m = np.mean(a, axis=0)
s = np.std(a, axis=0)
print(np.mean(a, axis=0))
print(np.std(a, axis=0))
a = (a - m)/s
print(a)

[ 2.5  3.5  4.5]
[ 1.5  1.5  1.5]
[[-1. -1. -1.]
 [ 1.  1.  1.]]
